### ISSUE TITLE
Bugfix

### ISSUE THREAD

**Issue by stschulze1972** [jsffm/vdr-transcode#3]
Zeile 3554 und 3557 -> statt 
videos=${videos:0:${#videos}-2}
audios=${audios:0:${#audios}-2}

besser:
videos=$(videos:0:${#videos}-2)
audios=$(audios:0:${#audios}-2)

oder ;-)

hatte fehler ...ich denke damit sollte es funktionieren ...mal sehen

**Comment by jsffm** [comment]
videos=${videos:0:${#videos}-2}
audios=${audios:0:${#audios}-2}

ist korrekt
